### ISSUE TITLE
Holoparasite doesnt die after the owner is turned into a slime simplemob and killed.

### ISSUE THREAD

**Issue by KevinTheGreat333** [fulpstation/fulpstation#1007]
## Reproduction: a guy had a holoparasite (explosion type) in him, then a wizard polymorphed him into a slime then killed him, though the holoparasite stayed alive.
1. give a guy a holoparasite
2. polymorph him into a slime (or any other mob(i only seen it done with a slime))
3. kill the slime.
4. the holoparasite is still alive by that point.

**Comment by remove32** [comment]
we haven't changed anything regarding holoparasites to my knowledge - if this does happen, it's likely a TG issue (which may have been resolved already due to the age of this ticket and our update process lag)
