### ISSUE TITLE
Bloodsuckers are trapped in coffin if they go into frenzy right before getting in

### ISSUE THREAD

**Issue by Okram0** [fulpstation/fulpstation#1008]
Round ID: [26512](https://scrubby.melonmesa.com/round/26512)

## Reproduction:

Go into frenzy as a bloodsucker and then hop into a coffin, the damage from frenzy prevents healing and you are just stuck there forever.

**Comment by Okram0** [comment]
Update: The healing ever so slightly outpaces the damage but your still trapped there for like 30 mins

**Comment by JohnFulpWillard** [comment]
It’s sorta intended as frenzy is meant to kill you even if you’re in a coffin, and the extra time it gives is so vassals can find you, but it does seem kinda boring. Wonder what we can do about it

**Comment by remove32** [comment]
could prevent torpor based on logic of "agh i'm so awake".
