### ISSUE TITLE
SDQL2 might be vulnerable

### ISSUE THREAD

**Issue by DrPepperIsSpicy** [fulpstation/fulpstation#1014]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
https://github.com/tgstation/tgstation/pull/76276

**Comment by DrPepperIsSpicy** [comment]
To clarify, this is only an issue if an xss vulnerability is present, meaning text is reflected unsanitized to players in some way. The issue is that the verb can be fed using a feature implemented by byond like ?winset to run the verb with params. The verb is very powerful, essentially a tiny scripting language so it shouldn't be accessible in this manner(instead fed using an input shown directly to the user, or confirmed before executing)

**Comment by remove32** [comment]
we received the resolution from TG upstream already - this should no longer be an issue
