### ISSUE TITLE
Supply shuttle launches with people in it

### ISSUE THREAD

**Issue by Gr1lledcheese** [fulpstation/fulpstation#102]
## Round ID: 
[13774](https://scrubby.melonmesa.com/round/13774)

## Testmerges:
The following pull requests are currently test merged:
#97: 'Bloodsuckers' by JohnFulpWillard at commit abf2cae30b

## Reproduction:
1. Play as deputy, which is what I was at the time. (test other roles if you wish)
2.  Hit the launch button. (Do this after step 3 if there isn't a delay before launching, can't remember if there is)
3. Board the cargo shuttle.
4. Reach centcom and you will be ghosted by the game.

**Comment by JohnFulpWillard** [comment]
https://github.com/tgstation/tgstation/pull/58201

This is the PR that fixes it, we'll have the fix when TGU is merged

**Comment by Helianthus00** [comment]
closed, since this is a /tg/ issue
