### ISSUE TITLE
Changeling reviving stasis doesn't work

### ISSUE THREAD

**Issue by DeaddFish** [fulpstation/fulpstation#1027]
Round ID: [27186](https://scrubby.melonmesa.com/round/27186)

## Reproduction: 
die as a ling then try to use reviving stasis, gives the "We begin our stasis, preparing energy to arise once more." but doesn't do anything no matter how long I wait, my head was cut off when it happened tho I don't think that has anything to do with it.

**Comment by destrucktoid** [comment]
Did you click the button to revive once the stasis had charged? Or did the button not appear?

**Comment by Honkers-the-clown** [comment]
> Did you click the button to revive once the stasis had charged? Or did the button not appear?

Just tested it, the button never changes to the revive button and you are stuck dead

**Comment by SgtHunk** [comment]
tg issue, fixed when we tgu

**Comment by Honkers-the-clown** [comment]
Based
