### ISSUE TITLE
Birdshot Disposals recycler is fundementally Broken

### ISSUE THREAD

**Issue by nintyuk** [fulpstation/fulpstation#1041]
## Reproduction:
The Birdshot Disposals Recycler is setup to take input from below but the recycler can only take input from the sides. 
![image](https://github.com/fulpstation/fulpstation/assets/4965151/571fa329-7d66-4225-9864-77bcc6db1c23)

The recycler either needs a rotated sprite to allow it to run vertically or the entire room needs to be re-designed

**Comment by remove32** [comment]
Birdshot is upstream, but doesn't have a webmap so I'm not 100% sure the current state of it. Looking at the DMM manually, it does look like the recycler still has default rotation, which would presumably still cause this issue even upstream. Regardless, we don't maintain it here, so if you'd like you could report it upstream (I recommend checking on TG manually first if you decide to do so). Thanks for reporting it though 😃

**Comment by nintyuk** [comment]
> Birdshot is upstream, but doesn't have a webmap so I'm not 100% sure the current state of it. Looking at the DMM manually, it does look like the recycler still has default rotation, which would presumably still cause this issue even upstream. Regardless, we don't maintain it here, so if you'd like you could report it upstream (I recommend checking on TG manually first if you decide to do so). Thanks for reporting it though 😃
https://affectedarc07.github.io/SS13WebMap/Effigy/Birdshot/ webmap
