### ISSUE TITLE
bloodsucker UI no work after TGU

### ISSUE THREAD

**Issue by Sadboysuss** [fulpstation/fulpstation#1132]
## Issue Summary

![image](https://github.com/fulpstation/fulpstation/assets/96586172/1c45a79b-39d8-4ce5-9d51-7541471350cc)
 no work

**Comment by Sadboysuss** [comment]
![image](https://github.com/fulpstation/fulpstation/assets/96586172/501ef7f7-1936-4453-b3e8-4bcfd9b93f8a)
antag tips overall seems to be non functioning

**Comment by Bilbo367** [comment]
![image](https://github.com/fulpstation/fulpstation/assets/163439532/51457147-2afd-4dd4-af1f-3abd32a51448)
No? but Monster hunter isn't getting objectives. It could be an issue from another TM?

**Comment by Bilbo367** [comment]
This is issue is old. And should probably be closed.
