### ISSUE TITLE
round end audio message is wrong

### ISSUE THREAD

**Issue by Sadboysuss** [fulpstation/fulpstation#1133]
## Issue Summary

after TGU, round end audio message is now the ones used in TG

**Comment by JohnFulpWillard** [comment]
This was after TGS update, not by TGU

**Comment by JohnFulpWillard** [comment]
It's also what broke round timers

**Comment by Sadboysuss** [comment]
ah ok

**Comment by remove32** [comment]
not an issue, fulp audio is also included. admin team controls this so if they want to remove tg audio they just need to do it or ask me to do it
