### ISSUE TITLE
HelioStation Spare cap ID hangs on a normal wall

### ISSUE THREAD

**Issue by Sadboysuss** [fulpstation/fulpstation#1137]
## Issue Summary

![image](https://github.com/fulpstation/fulpstation/assets/96586172/19014817-b52e-470a-8906-99ed7c8bc334)

deconstructing the wall the safe sits on will drop the ID, all maps have R-walls instead

**Comment by JohnFulpWillard** [comment]
it will be fine next tgu when it's taken off the wall

**Comment by Sadboysuss** [comment]
Closed by https://github.com/fulpstation/fulpstation/pull/1146
