### ISSUE TITLE
Parrots eat headsets for breakfast

### ISSUE THREAD

**Issue by BanementI** [fulpstation/fulpstation#1143]
## Issue Summary

When placing a headset on a parrot that is not Poly, the headset will disappear and not be on the parrot. It's like the parrot straight up ate it.

## Round ID: 
[31159](https://scrubby.melonmesa.com/round/31159)

## Testmerges:

[#1107: 'Adds Fulpstation Station' by Horatio22 at commit e53b9be50e](https://github.com/fulpstation/fulpstation/pull/1107)
[#1138: 'fix beefmen hair not matching their meat's color' by Ben10Omintrix at commit 5ff089cca8](https://github.com/fulpstation/fulpstation/pull/1138)
[#1131: 'Adds a Pubby Courtroom' by Cure221 at commit 7dbf900080](https://github.com/fulpstation/fulpstation/pull/1131)
[#1135: 'Nanite fix1' by pleonektein at commit 0fdecc46d9](https://github.com/fulpstation/fulpstation/pull/1135)

## Reproduction:

1. Find a parrot that isn't Poly (there's one in Fulp Station engineer maintenance).
2. Place headset on the parrot.
3. Headset gets destroyed.

**Comment by Sadboysuss** [comment]
Upstream issue I think

**Comment by Horatio22** [comment]
/tg/ issue

**Comment by Sadboysuss** [comment]
I'll post your issue on the /tg/ git
