### ISSUE TITLE
Minor access bug on selene

### ISSUE THREAD

**Issue by Sadboysuss** [fulpstation/fulpstation#1150]
## Issue Summary

Apparently you can walk into chapel office through maints with maint access, this is on Selene station

## Testmerges

Maybe this? https://github.com/fulpstation/fulpstation/pull/1144

**Comment by Bilbo367** [comment]
Should this issue be closed or is it still a problem?

**Comment by Sadboysuss** [comment]
> Should this issue be closed or is it still a problem?

I don't think anyone fixed it yet
