### ISSUE TITLE
The clown's bike horn does not make a sound when honking 

### ISSUE THREAD

**Issue by Squishypone** [fulpstation/fulpstation#168]
## Testmerges: none
TGU - Gamemode removal, GAGS & More 

## Reproduction:
1.) become clown 
2.) use the bike horn with the interactive or hitting someone with it
3.) feel sad for lack of honk

 
I don't know why it's doing it I just want to honk some people

**Comment by SgtHunk** [comment]
TG issue - PR already up on their end

**Comment by Helianthus00** [comment]
Fixed by #183
