### ISSUE TITLE
Beefmen

### ISSUE THREAD

**Issue by remove32** [fulpstation/fulpstation#2]
Port beefmen from the old repo

**Comment by GuillaumePrata** [comment]
I have most of the code done, will just double check tomorrow if anything was broken with the last updates on TG over December and likely will make a PR tomorrow.

**Comment by remove32** [comment]
The only thing I've noticed in TMing this is that they don't seem to bleed properly. They start with some bleed, but the bleed stops quickly and beefmen naturally regenerate blood.

**Comment by remove32** [comment]
Oh, also the phobetor tears aren't working
