### ISSUE TITLE
Split personality swapping broken

### ISSUE THREAD

**Issue by ModDownloading** [fulpstation/fulpstation#28]
Fulpstation is using older, unfixed code for the Split Personality trauma, so the second personality never actually switches into the body. TG fixed this with a one-line change PR (PR tgstation#54610) and I think it should be fixed over on Fulp as well so Split Personality can actually work as intended.

Steps:

1. Get split personality trauma
2. Have someone else be the split personality
3. Notice the split personality never takes over the body, regardless of how long you wait

Since the repository changed, I figured I might as well repost this here for visibility.

**Comment by remove32** [comment]
https://github.com/fulpstation/fulpstation/blob/366e82ed51bc5db7ce6c743e3c65ca89b1f3cc5f/code/datums/brain_damage/split_personality.dm#L74 
the fix is already in the new repo
