### ISSUE TITLE
Chem dispenser drops my FPS to 8-2, nothing else does this, not even mass ammounts of genetic human monkeys.

### ISSUE THREAD

**Issue by SeanHitler** [fulpstation/fulpstation#354]
## Round ID:

Found it a long time ago, it still persists about 11 months later.
## Testmerges:

No idea what is causing this.

## Reproduction:

So, whenever i open the chem dispenser my framerate drops to 8-2 FPS, and this only happens with the chem dispenser, nothing else, as soon as i open it framerate drops and doesn't go back to normal until i close it. This happens every round with no exceptions.

happens every round no matter what.

**Comment by Helianthus00** [comment]
Are you sure this isn't a /tg/ issue?

**Comment by JohnFulpWillard** [comment]
should be fixed with this soon https://github.com/tgstation/tgstation/pull/60995

**Comment by SeanHitler** [comment]
> Are you sure this isn't a /tg/ issue?

This happens on all the servers, although most the servers that have chem dispensers are TG code based, and i have not tried chem dispensers on goon

**Comment by SeanHitler** [comment]
> should be fixed with this soon [tgstation/tgstation#60995](https://github.com/tgstation/tgstation/pull/60995)

Not sure if the tooltips are the problem, but will tell you they are.

**Comment by Helianthus00** [comment]
Fixed by #351
