### ISSUE TITLE
A shit connection of 15 secs,why fulp station...WHY

### ISSUE THREAD

**Issue by Sugoma10** [fulpstation/fulpstation#435]
Reporting client version: 514.1571

## Round ID:
[17935](https://scrubby.melonmesa.com/round/17935)

## Testmerges:
- [Create Solitairestation.dmm](https://github.com/fulpstation/fulpstation/pull/290)
- [My attempt at Beefmen code improvements](https://github.com/fulpstation/fulpstation/pull/432)

**Comment by Helianthus00** [comment]
I have no idea what this means. You'll have to give more detail .
