### ISSUE TITLE
Modsuits: slime speed potions don't reduce movement penalty of modsuits.

### ISSUE THREAD

**Issue by MikeSNC** [fulpstation/fulpstation#452]
Reporting client version: 514.1566

## Round ID:
[18226](https://scrubby.melonmesa.com/round/18226)

## Testmerges: 
- [[Solitaire] Science Overhaul](https://github.com/fulpstation/fulpstation/pull/448)

## Reproduction:
Slime Speed Potions don't reduce modsuit movement speed penalty.  (My particular case was with the RD's shiftstart modsuit with no modifications.)
REPRO:
1. In Xenobiology create a Slime Speed Potion by syringing water into a red slime extract.
2. With the potion in hand, click your modsuit's "backpack" to apply it (turn it red).
3. Observe that the movement speed penalty of the modsuit hasn't been reduced.
EXPECTED RESULT:
Slime Speed Potions are supposed to remove the speed penalty of clothing they're applied to.  (Or at least reduce the penalty, as I think removing it entirely makes these potions feel a bit too good.)

**Comment by Helianthus00** [comment]
This is a tg issue. Please report it upstream if it hasn't been fixed there yet.

**Comment by JohnFulpWillard** [comment]
fixed with https://github.com/tgstation/tgstation/pull/63670
