### ISSUE TITLE
Can't enter non-integer numbers for musical instrument sustain duration

### ISSUE THREAD

**Issue by MikeSNC** [fulpstation/fulpstation#532]
Reporting client version: 514.1566

## Round ID:
[18944](https://scrubby.melonmesa.com/round/18944)

## Testmerges:
- [Perma expansion 2](https://github.com/fulpstation/fulpstation/pull/508)

## Reproduction:
REPRO:
1. Press USE while holding a musical instrument (eg Synthesizer) to open the music menu.
2. Click Linear Sustain Duration
3. Enter 0.3 (secs) and SUBMIT.
4. Observe that the number is set to 3.0 seconds instead of 0.3

EXPECTED:  you should be able to set non-integer values in this field, because you could before recent changes to this dialog (and also because faster-paced songs will drop notes if the sustain isn't short enough).

**Comment by Sheits** [comment]
this sounds like an issue with our upstream, which deals with almost all code but the fulp unique stuff (beefmen, bloodsuckers) you can report bugs at https://github.com/tgstation/tgstation/issues

**Comment by Helianthus00** [comment]
TG issue
