### ISSUE TITLE
Using Roller Skates on Z-level tile transition allows you to 'levitate'

### ISSUE THREAD

**Issue by RazorManager89** [fulpstation/fulpstation#537]
Round ID: [19006](https://scrubby.melonmesa.com/round/19006) (fulpstation)

## Reproduction
Deploy the roller skates' wheels while moving onto a Z level. This can usually be reproduced while trying to move down from the Library to the Chapel on Icebox.

## Comments
This is my first bug report, so I hope I don't get anything wrong with the formatting.

![image](https://user-images.githubusercontent.com/37266586/155168783-dff06c3d-72db-4601-8110-46b67607e8a2.png)

**Comment by Ebb-Real** [comment]
roller skates are a TG thing from the upstream, so it should go here https://github.com/tgstation/tgstation/issues

this repo is for fulp specific stuff and edits of the upstream

**Comment by Helianthus00** [comment]
tg issue
