### ISSUE TITLE
Heliostation Perma Labor shuttle doesn't appear

### ISSUE THREAD

**Issue by ModDownloading** [fulpstation/fulpstation#659]
## Round ID:

[20754](https://scrubby.melonmesa.com/round/20754)

## Testmerges:

#652 

## Reproduction:

The perma shuttle (from #508) isn't on Heliostation in the most recent merge. I think this is a bug caused by #652 since the perma shuttle and perma shuttle dock were both there when I downloaded the source code and ran it myself on a private test server. Hopefully the perma shuttle gets added back soon, I really liked doing most of the tasks (except the junkmail sorting one, that doesn't give you nearly enough time).

**Comment by JohnFulpWillard** [comment]
> > Did it work locally?
> 
> i thought u readded them

Added it now

**Comment by ModDownloading** [comment]
Thanks guys, the Heliostation perma shuttle dock is back.

I don't think it's in the right place though:

![Fulpstation Garbage Continent Epsilon 2022-06-16 170736](https://user-images.githubusercontent.com/25691743/174163890-51dea78c-2ead-4fbe-a660-dc7584eb8713.png)
