### ISSUE TITLE
Bloodsucker/Vassal antag huds are broken

### ISSUE THREAD

**Issue by JohnFulpWillard** [fulpstation/fulpstation#676]
## Reproduction:

1) Get vassalized
2) Can't see your own antag HUD, your master bloodsucker's, or any other vassal's.

Bloodsuckers however can see all vassal icons regardless of the vassal is even theirs.

**Comment by SgtHunk** [comment]
Fixed by https://github.com/fulpstation/fulpstation/pull/748
