### ISSUE TITLE
Beefmen's lore is way too long without any breaks

### ISSUE THREAD

**Issue by JohnFulpWillard** [fulpstation/fulpstation#681]
## Reproduction:

![image](https://user-images.githubusercontent.com/53777086/175658549-cf6a66f0-b9fc-4517-afae-2b48c52422c3.png)

lizard for comparison:
![image](https://user-images.githubusercontent.com/53777086/175658576-a4975581-9a3b-4a51-8b79-d4f564b39f06.png)

**Comment by Pepsilawn** [comment]
U fucker wrote that shit
