### ISSUE TITLE
The MOTD's Testmerges brings you to TheSwain/Fulpstation instead of Fulpstation/Fulpstation

### ISSUE THREAD

**Issue by JohnFulpWillard** [fulpstation/fulpstation#73]
## Reproduction:

Click on the OOC tab, click MOTD. Click on one of the testmerges, brings you TheSwain/Fulpstation. Replacing 'TheSwain' for 'Fulpstation' brings you to the actual testmerge.

![Screenshot (1775)](https://user-images.githubusercontent.com/53777086/111234146-4acd8800-85c4-11eb-8274-f363951fbf19.png)

**Comment by EgorDinamit** [comment]
Config issue.

**Comment by Helianthus00** [comment]
actually not fixed

**Comment by Helianthus00** [comment]
actually is fixed
