### ISSUE TITLE
heliostation cargo and AI sat isn't connected to station power

### ISSUE THREAD

**Issue by BlueMemesauce** [fulpstation/fulpstation#828]
![image](https://user-images.githubusercontent.com/47338680/194738224-dce2e6e1-bd01-4d51-9d5f-cea13566596f.png)

Even though they aren't connected to the station power, they seem fine at roundstart due to the AI sat SMES providing power. However,  the SMES runs out after an hour or so, which leaves the AI sat and cargo without power. How has nobody noticed this before?

fulp moment

**Comment by OperativeLyn** [comment]
It is connected through the maints below cargo

**Comment by Pepsilawn** [comment]
Good

**Comment by BlueMemesauce** [comment]
> It is connected through the maints below cargo, but a single mouse can ruin cargo and AI sat power, which sucks.

![image](https://user-images.githubusercontent.com/47338680/194778246-40e64faf-61a2-40e3-9033-8f0a940ad522.png)

you're right, it goes all the way around maint i didnt even see that
