### ISSUE TITLE
Dsword invalidated by thrown baton

### ISSUE THREAD

**Issue by Okram0** [fulpstation/fulpstation#853]
## Reproduction:
If a baton is thrown at a d-sword wielder then it works, utterly invalidating the blocking if that lone sec off you just cornered remembers to use the throw command. baton has to be on. 99% sure this isn't a feature since it removes the purpose of the D-sword blocking batons

**Comment by FernandoJ8** [comment]
A) this is a tg issue, not a fulp issue
B) it only has a 35% chance to stun when thrown, which is barely better than the chance to not be blocked

**Comment by Pepsilawn** [comment]
Its harder to block a projectile like that thrown at full force than a melee weapon swing irl too

**Comment by Okram0** [comment]
Checked and confirmed to be my bad luck not an actual game issue. Thought it was an oversight where baton would just go through 100% of the time, instead was just my luck. Also, I encountered it on fulp so fulp issue was my logic

**Comment by JohnFulpWillard** [comment]
fulp issue reporting is weird so it would be nice if there was some guide on what to report and what not to report (or what to report on TG instead)
