### ISSUE TITLE
Ocky icky beefman are terrified of the term for referring to a group of people

### ISSUE THREAD

**Issue by BanementI** [fulpstation/fulpstation#858]
Reporting client version: 514.1588

## Round ID:
[23421](https://scrubby.melonmesa.com/round/23421)

## Testmerges:
- [Bloodsucker expansion: Favorites and Revenge vassals](https://github.com/fulpstation/fulpstation/pull/783)

## Reproduction:
0.5. Get the ocky icky phobia.
1. Try to say "Us" or hear someone say "Us" over the radio.
2. Get scared.
![05-12-2022 21-23-05](https://user-images.githubusercontent.com/47301693/205745404-bcbf71ba-d81a-465b-9517-392efad681d1.png)

Also works with "my".

**Comment by remove32** [comment]
Tested this just now - played a round as beefman with that phobia but never encountered that. I assume that in the time since you entered this issue, it was fixed upstream and we imported that fix. Thank you for reporting it though
