### ISSUE TITLE
[Heliostation] AI sat entrance isnt connected to AI sat

### ISSUE THREAD

**Issue by JohnFulpWillard** [fulpstation/fulpstation#864]
## Reproduction:

This requires a crowbar to open because it's not part of the sat

![image](https://user-images.githubusercontent.com/53777086/206899831-0ebb2fe3-9832-49fe-af56-418cd9541188.png)

**Comment by OneAsianTortoise** [comment]
LoL my bad I wll fix it as soon as I gets home
