### ISSUE TITLE
Ventrue can purchase flow for their favorite vassal

### ISSUE THREAD

**Issue by Looks-to-the-Moon** [fulpstation/fulpstation#888]
## Round ID:

[24132](https://scrubby.melonmesa.com/round/24132)

## Reproduction:

Be sucker, make favorite vassal, buckle to candelabrum, teach them flow.

I imagine this will be fixed when smokey moves monster hunter shit out of bloodsucker code

**Comment by JohnFulpWillard** [comment]
Fixed by https://github.com/fulpstation/fulpstation/pull/884
