### ISSUE TITLE
Helio xenos have a 1/9 chance to be softlocked

### ISSUE THREAD

**Issue by Pepsilawn** [fulpstation/fulpstation#897]
Reproduction: Above the atmos distro room there is a room without any scrubber/vent thats locked with an airlock with the abandoned effect helper, which has a chance to replace the airlock with a closed turf and blocking any chance for the spawn to actually do anything

![image](https://user-images.githubusercontent.com/25415050/215341148-c301a963-0230-4b38-9271-bcbece5c5d49.png)

**Comment by FernandoJ8** [comment]
I like this feature

**Comment by OneAsianTortoise** [comment]
who did that...

**Comment by JohnFulpWillard** [comment]
alien queen spit moment
