### ISSUE TITLE
List of issue in selene engi

### ISSUE THREAD

**Issue by OneAsianTortoise** [fulpstation/fulpstation#898]
## Issues:

- Anyone with tcomm access can enter CE office from T comm.
- CE cannot use the buttons in his office.
- No CE stamp.
- No secure storage
- Engi can enter sec outpost
- Green pipes not connected to loop
- No reset module in tech storage
- There's air alarm in tcomm...

**Comment by Pepsilawn** [comment]
lol

**Comment by Cass-Bitchcoin** [comment]
If I may add to this,

* The only fire alarms are in tcomms and by the incinerator. 
* The portable air pump connectors in the lobby are connected to green pipes that don't seem to be connected to anything.
* ~~Engineers are supplied with a whole 5 sheets of iron and no glass to build with at round start~~ There is also a single full stack of iron in the corner of the engine room
* There are no plasma and temperature stabilizer modules
* No microwave to heat my donk pockets :c

**Comment by KittyNoodle** [comment]
The insuls are also hidden away in maints for some reason

**Comment by KittyNoodle** [comment]
the in-window pipes in selene atmos do not have layer adapters, this completely deviates from the setup on all other stations and makes additions to atmos very hard
