### ISSUE TITLE
Helio cable issues

### ISSUE THREAD

**Issue by JohnFulpWillard** [fulpstation/fulpstation#923]
## Reproduction:

Cable at the HoP line doesn't connect with the cables in maints
![image](https://user-images.githubusercontent.com/53777086/220189349-c6913e6a-d617-4512-b48d-c2a6e1dc86cd.png)

Service hall cables, engineering maintenance cables, and hallway cables don't connect
![image](https://user-images.githubusercontent.com/53777086/220189454-de167238-3bfb-4eff-a2f6-653519a6ec09.png)

Above tech storage, there's 6 cables all next to eachother
![image](https://user-images.githubusercontent.com/53777086/220189538-4e3f223e-7ea0-4c26-80ba-d260250371a7.png)

Same for Cargo entrance at the civilian bounty pad
![image](https://user-images.githubusercontent.com/53777086/220189608-3f229fbb-608c-4454-96fa-9fa5900851ad.png)

Det office seems to want to connect with the hallways but it just doesn't
![image](https://user-images.githubusercontent.com/53777086/220189690-056a0598-6868-4176-b2b6-93a59076c685.png)

Right side of the AI's solars makes it seem like they want the solar panels directly connected to the grid
![image](https://user-images.githubusercontent.com/53777086/220189854-400dec47-920e-44e6-867f-0073a6f6a280.png)

**Comment by OneAsianTortoise** [comment]
The cable should be linear instead of all connected but yeah they may need better placement.
