### ISSUE TITLE
[Heliostation] Poly isn't real

### ISSUE THREAD

**Issue by JohnFulpWillard** [fulpstation/fulpstation#926]
![image](https://user-images.githubusercontent.com/53777086/221796390-1d0f245c-0417-478c-8d12-4cb499c9715b.png)
![image](https://user-images.githubusercontent.com/53777086/221796417-4ec5da28-18b3-43a4-87ab-0c0fdde889d8.png)

btfo engineering traitors lol

**Comment by OneAsianTortoise** [comment]
Sry but I don't like bird.
