### ISSUE TITLE
[Selene] Ordnance cold chamber isn't properly connected

### ISSUE THREAD

**Issue by Pepsilawn** [fulpstation/fulpstation#937]
![image](https://user-images.githubusercontent.com/25415050/226215122-cb3347a6-0d23-4c92-a196-9dd684322f5f.png)

Try to cool your gases, can't because the HE pipes aren't receiving any gases

**Comment by SmoSmoSmoSmok** [comment]
arent u the asshole who designed it

**Comment by Pepsilawn** [comment]
I was being possessed by an otherworldly demon
