### ISSUE TITLE
Bloodsuckers cant make fav vassals 

### ISSUE THREAD

**Issue by Okram0** [fulpstation/fulpstation#993]
## Reproduction:
Attempt to make someone a favorite vassal, fail. this could be that fav vassals were changed, and nobody knows, but both as a bloodsucker and as a vassal who was going to be fav nobody could figure it out since clicking on rack no longer works.

**Comment by JohnFulpWillard** [comment]
What clan were you part of?

**Comment by Okram0** [comment]
Well when i was the bloodsucker tremere, and the person who attempted it on me was nosferatu

**Comment by JohnFulpWillard** [comment]
Found the bug, fixed in the PR that just mentioned this issue.
