### ISSUE TITLE
Vanishing Act on Bloodsucker doesn't work

### ISSUE THREAD

**Issue by carlopault** [fulpstation/fulpstation#997]
## Reproduction:

You click it and it does nothing. It does not teleport you to your claimed coffin. I was the "Classic Bloodsucker" clan

**Comment by remove32** [comment]
The code is set up in a slightly odd way, so it isn't displaying a progress bar. It does seem to work though, it just takes a couple of seconds to complete the teleport. I think you need to hold still.
